version: '3.8'

services:
  llamacpp-backend:
    image: llamacpp-backend
    build:
      context: llamacpp-python-server
    ports:
      - "8000:8000"
    command: ["python3", "-m", "llama_cpp.server", "--hf_model_repo_id", "${MODEL_REPO}", "--model", "${MODEL_NAME}", "--port", "8000", "--host", "0.0.0.0"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      internal:
        aliases:
          - backend

#  frontend-cli:
#    image: llamacpp-go-frontend-cli
#    build:
#      context: frontend-cli
#    container_name: frontend-cli
#    networks:
#      internal:

networks:
  internal:
    driver: bridge