version: '3.8'

services:
  llamacpp-backend:
    image: llamacpp-backend
    build:
      context: docker/llamacpp-python
    ports:
      - "8000:8000"
    volumes:
      - ./model-gguf:/models
    command: ["python3", "-m", "llama_cpp.server", "--model", "/models/${MODEL_NAME}.gguf", "--port", "8000", "--host", "0.0.0.0"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]