version: '3.8'

services:
  llamacpp-backend:
    image: llamacpp-backend
    build:
      context: docker/llamacpp-python
    ports:
      - "8000:8000"
    command: ["python3", "-m", "llama_cpp.server", "--hf_model_repo_id", "${MODEL_REPO}", "--model", "${MODEL_NAME}", "--port", "8000", "--host", "0.0.0.0"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]